FLASHINGLED_VERSION = 1.0
FLASHINGLED_SITE = $(TOPDIR)/package/flashingled
FLASHINGLED_SITE_METHOD = local
FLASHINGLED_LICENSE = MIT

FLASHINGLED_DEPENDENCIES = linux

define FLASHINGLED_BUILD_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D)
endef

define FLASHINGLED_INSTALL_TARGET_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D) modules_install
endef

$(eval $(generic-package))
