FLASHINGLED_DRIVER_VERSION = 1.0
FLASHINGLED_DRIVER_SITE = $(TOPDIR)/package/flashingled-driver
FLASHINGLED_DRIVER_SITE_METHOD = local
FLASHINGLED_DRIVER_LICENSE = MIT

FLASHINGLED_DRIVER_DEPENDENCIES = linux

define FLASHINGLED_DRIVER_BUILD_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D)
endef

define FLASHINGLED_DRIVEr_INSTALL_TARGET_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D) modules_install
endef

$(eval $(generic-package))
